touch $1/instructions.h
chmod +w $1/instructions.h
echo "// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED BY THE MAKEFILE (see target for instructions.h)" > $1/instructions.h
echo "#include \"ptx_ir.h\"" >> $1/instructions.h
echo "#ifndef instructions_h_included" >> $1/instructions.h
echo "#define instructions_h_included" >> $1/instructions.h
cat $2/instructions.cc | grep "_impl(" | sed 's/{.*//' | sed 's/$/;/' >> $1/instructions.h
echo "#endif" >> $1/instructions.h
chmod -w $1/instructions.h


cat $2/ptx.tab.h | grep "=" | sed 's/^[ ]\+//' | sed 's/[=,]//g' | sed 's/\([_A-Z1-9]\+\)[ ]\+\([0-9]\+\)/\1 \1/' | sed 's/^/DEF(/' | sed 's/ /,"/' | sed 's/$/")/' > $1/ptx_parser_decode.def
